### ISSUE TITLE
Chrome extension: researcher

### ISSUE THREAD

**Issue by Strajk** [Strajk/ideas#2]
Show HN, reddit, twitter, ... links to this site

**Comment by underyx** [comment]
- [reddit companion](https://chrome.google.com/webstore/detail/reddit-companion/algjnflpgoopkdijmkalfcifomdhmcbe) does this for websites on reddit.
- [alientube](https://chrome.google.com/webstore/detail/alientube-for-youtube/opgodjgjgojjkhlmmhdlojfehcemknnp?hl=en) does this for youtube videos on reddit.

**Comment by Strajk** [comment]
Reddit companion is exactly what I wanted!

Found updated fork:

* https://github.com/creesch/reddit-companion
* https://chrome.google.com/webstore/detail/companion-for-reddit/hjndgefhmfcgpoocjcgoemphhdkbhipm
